### PR TITLE
hosts/mapi: Fix syntax error

### PR DESCRIPTION
**Pull request by LukeShu**
The `mapi` host file contains am "empty" line that actually has 2 spaces.
I don't know if previous versions of tinc were more lax, but as of
tinc-1.0.33, this is an error:

    No value for variable `' on line 8 while reading config file /etc/tinc/lvpn/hosts/mapi

The "=" is optional (if there's whitespace), and it trims leading+trailing
whitespace on the value, so it interprets the line as setting the ""
variable to an empty value.

### CODE REVIEW

**Comment by fauno** [comment]
i think we can just remove all of hosts/ since they're mostly dead anyway.

in the plans that i had we wouldn't be publishing nodes on the internet :P

-- 
:>

**Comment by LukeShu** [comment]
I wrote a program to monitor the availability of the public nodes that you can `ConnectTo`, because I thought that would be a fun thing to graph.

Well, the *only* `Address` in `hosts/*` that is currently available is `parabola.nu:655`.

**Comment by LukeShu** [comment]
Oh, I wonder if that has to do with #7, I should add ping to the program to see if the host is online, and just not running `tinc@lvpn`.

**Comment by fauno** [comment]
iirc i added a flag to `lvpn connectto` to ping the remote nodes before adding them.  maybe it's in the branch i never finished...

i need to get back to work on lvpn! :)

**Comment by LukeShu** [comment]
>  in the plans that i had we wouldn't be publishing nodes on the internet :P

So how would we distribute host files?

**Comment by fauno** [comment]
there's a wip branch feature/intercambio-automatico

they would be distributed from inside the network and you'd only need an
introductor node to be part of it.

once bootstraped, every node would have every host file, so connectto
would be a one sided process instead of a coordinating effort.

i was working on a sort of key server using a git repo for host files,
served over an adhoc sshd, and some cronjob to pull.  i don't know why i
didn't just use git-daemon, but also was looking at other stuffs that
didn't require people to add keyservers to pull from, like uftp.  now
that syncthing exists it could use that, though both uftp and syncthing
would lack history of modifications and syncthing would be a little
heavy on resources.

anyway by that time people had lost interest in librevpn and i was just
using it for my servers, so the manual process was enough.  it had also
to be with me pushing for this to happen my way and driving
contributions away :(


-- 
P)

**Pull request closed without merging**
