### PR TITLE
Improve Makefile

### PR DESCRIPTION
**Pull request by LukeShu**
- Update the Makefile to generate man pages correctly with modern Pandoc
 - Fix `make BUILD_UPNPC=true` (it expects it at `etc/miniupnpc`, but it was actually at etc/miniupnpc/miniupnpc`
 - Teach the Makefile `make lvpn` to generate `./lvpn` from `lvpn.in`; I was confused, writing this change helped me be less confused

### CODE REVIEW

**Comment by fauno** [comment]
thanks!

the split between `lvpn` and `lvpn.in` is that the first is meant to be used from within the repo and the latter to be installed, that's why some variables are different.

i'll need some time to review this, i've also developed a simpler way to have `make` build templates, using envsubst, though it's a bit problematic for bash scripts, since envsubst will replace `${undefined_variable}` with a blank string

**Comment by LukeShu** [comment]
> the split between `lvpn` and `lvpn.in` is that the first is meant to be used from within the repo and the latter to be installed, that's why some variables are different.

Yes, I hadn't realized that in #4; and broke it there (which is why I closed it once I realized).

The included commit uses target-private Make variables[1] to have different `@VAR@` substitutions for `lvpn.in -> lvpn` and `lvpn.in -> lvpn.out`, to keep this difference.

I detailed in the commit message the few compromises in each to generate both versions from the same source.  But, you don't have to take my word for it:
 - I left `lvpn` checked in to git, you can see in the commit diff exactly how it changed, and
 - you can run `make lvpn.out` before and after checkout out this PR and diff them; but for your convenience, here it is:

```patch
--- lvpn.out.old	2018-02-02 21:42:37.477575931 -0500
+++ lvpn.out	2018-02-02 21:42:48.180681290 -0500
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# lvpn.in
+# lvpn
 #
 # Copyright (c) 2011-2013 LibreVPN <vpn@hackcoop.com.ar>
 #
@@ -21,7 +21,6 @@
 # <http://www.gnu.org/licenses/>.
 #
 #
-# Versión autogenerada
 # Wrapper para correr los comandos al estilo `git comando parametros`
 # Hay que crearlos en libdir/lvpn-comando
 
@@ -30,9 +29,9 @@
 # o de la shell) o usar directorios locales
 TINC="${TINC:-"/etc/tinc/lvpn"}"
 NETWORK="${NETWORK:-"lvpn"}"
-LVPN="/usr/local/bin/lvpn"
-# Guardar todo en el ~/.config del usuario local
-LVPN_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/${NETWORK}"
+LVPN="$(readlink -f $0)"
+
+LVPN_DIR="${LVPN_DIR:-"${XDG_CONFIG_HOME:-${HOME}/.config}/${NETWORK}"}"
 LVPN_CONTRIB="${LVPN_CONTRIB:-"/usr/local/share/lvpn/contrib"}"
 LVPN_LIBDIR="${LVPN_LIBDIR:-"/usr/local/lib/lvpn"}"
 LVPN_HOSTS="${LVPN_HOSTS:-"/usr/local/share/lvpn/hosts"}"
@@ -55,6 +54,8 @@
        KEYSIZE TEXTDOMAINDIR TEXTDOMAIN \
        LVPN_SUBNET LVPN_SUBNET6 TINCD_FLAGS PORT
 
+export PATH="${LVPN_DIR}/bin:$PATH"
+
 . "${LVPN_LIBDIR}/common"
 
 list_commands() {

```

[1]: now that I think of it, are a pretty recent private variables are a pretty recent feature in GNU Make; sometime after 4.0, IIRC.  IDK if that's a problem, I don't know what other distros are shipping.

Would you like me to split this into multiple PRs? The "Makefile, doc: update rule for modern Pandoc" and "Makefile: fix BUILD_UPNPC=true" may be applied (cherry picked) separately from the other two.

**Comment by LukeShu** [comment]
Oh, I meant to add:

I was confused because I saw paths in `./lvpn`, and I didn't realize that my `/usr/bin/lvpn` was doing something different--this way it's more explicit *what* the differences are, and it isn't necessary to do more work to keep the two in sync.

**Comment by LukeShu** [comment]
I've split this in to 3 separate pull requests, because it's really doing 3 different things. #6, #8, and #9.

**Pull request closed without merging**
